# Site settings
title: porco's chips
url: "https://porcochips.github.io"
baseurl: ""
description: ""

# My information
email: porcochips+blog@gmail.com
author: porco
profile: 이것저것 합니다.
twitter_username: ""
github_username: porcochips
comment-support: giscus

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: porcochips/porcochips.github.io
  repo_id: R_kgDOSM5tzQ
  category: Announcements
  category_id: DIC_kwDOSM5tzc4C7uN6

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/porcochips/porcochips.github.io/blame/master/_wiki"
edit: "https://github.com/porcochips/porcochips.github.io/edit/master/_wiki"
issue: "https://github.com/porcochips/porcochips.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
